- name: Set Hostname
  ansible.builtin.shell: set-hostname sonarqube

- name: Add Sonarqube user
  ansible.builtin.user:
   name: sonarqube

# ----------------------------
# Install Java 21 (Temurin)
# ----------------------------

- name: Import Adoptium GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Add Adoptium repository
  ansible.builtin.yum_repository:
    name: Adoptium
    description: Adoptium Temurin Repository
    baseurl: https://packages.adoptium.net/artifactory/rpm/centos/8/x86_64
    enabled: true
    gpgcheck: true
    gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public

- name: Install Temurin 21 JDK
  ansible.builtin.dnf:
    name: temurin-21-jdk
    state: present

- name: Set vm.max_map_count for SonarQube
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "524288"
    state: present
    reload: yes

- name: Downlad Sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-26.2.0.119303.zip
    dest: /home/sonarqube
    remote_src: yes
    owner: sonarqube
    group: sonarqube
    recurse: yes


- name: Copy Sonarqube service file
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service



- name: Start Sonarqube service
  ansible.builtin.systemd_service:
    name: sonarqube
    daemon_reload: true
    state: restarted
    enabled: true
