- name: Set Hostname
  ansible.builtin.shell: set-hostname sonarqube

- name: Add Sonarqube user
  ansible.builtin.user:
   name: sonarqube

- name: Download Temurin 21 (LTS) tarball
  ansible.builtin.get_url:
    url: "https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse"
    dest: /opt/temurin-21.tar.gz
    mode: '0644'

- name: Extract Temurin 21
  ansible.builtin.unarchive:
    src: /opt/temurin-21.tar.gz
    dest: /opt/
    remote_src: yes

- name: Find extracted JDK directory
  ansible.builtin.find:
    paths: /opt
    patterns: "jdk-21*"
    file_type: directory
  register: jdk_dir

- name: Create stable java symlink
  ansible.builtin.file:
    src: "{{ jdk_dir.files[0].path }}"
    dest: /opt/java21
    state: link
    force: yes

- name: Set vm.max_map_count for SonarQube
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: "524288"
    state: present
    reload: yes

- name: Downlad Sonarqube
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-26.2.0.119303.zip
    dest: /home/sonarqube
    remote_src: yes
    owner: sonarqube
    group: sonarqube
    recurse: yes


- name: Copy Sonarqube service file
  ansible.builtin.template:
    src: sonarqube.service
    dest: /etc/systemd/system/sonarqube.service



- name: Start Sonarqube service
  ansible.builtin.systemd_service:
    name: sonarqube
    daemon_reload: true
    state: restarted
    enabled: true
