format_version: 10
pipelines:
  alb-remove:
    group: tools
    label_template: ${COUNT}
    materials:
      ansible:
        git: https://github.com/kn-10/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            deployment:
              timeout: 0
              tasks:
                - exec:
                    command: terraform
                    arguments: ["init"]


                - exec:
                    command: terraform
                    arguments: [ "destroy", "-auto-approve", "-target=module.alb" ]



