- name: Set Hostname For Server
  ansible.builtin.shell: set-hostname jenkins

- name: Copy Jenkins Repo File
  ansible.builtin.template:
    src: jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install Jenkins
  ansible.builtin.dnf:
    name:
      - fontconfig
      - java-17-openjdk
      - jenkins-2.462.3
    state: present

- name: Ensure Java 17 is default
  ansible.builtin.command:
    cmd: alternatives --set java /usr/lib/jvm/java-17-openjdk/bin/java

- name: Install Jenkins Python Library
  ansible.builtin.dnf:
    name: python3-jenkins.noarch
    state: present

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start Jenkins Service
  ansible.builtin.systemd_service:
    name: jenkins
    state: restarted
    enabled: true

#- name: Create a Job
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
#    name: "{{item}}"
#    password: admin123
#    url: http://jenkins-int.kdevops.online:8080
#    user: admin
#  loop:
#    - frontend
#    - catalogue
#    - cart
#    - user
#    - payment
#    - shipping
#    - dispatch
#    - parameter-store-init-container-image
#    - schema-loader

#- name: Create Multi Branch Pipeline Jobs
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'templates/multibranch.xml') }}"
#    name: "{{item}}"
#    password: admin
#    url: http://jenkins-int.kdevops.online:8080
#    user: admin
#  loop:
#    - frontend
#    - catalogue
#    - cart
#    - user
#    - payment
#    - shipping