input {
  beats {
    port => 5044
  }
}

filter {
  grok {
        match => {
          "message" => "%{IP:source_ip} %{TIMESTAMP_ISO8601:date} %{NUMBER:http_status:int} %{NUMBER:response_time:float} %{WORD:http_method} %{URIPATHPARAM:http_path} HTTP/%{NUMBER:http_version}"
        }
        tag_on_failure => ["_grokparsefailure"]
      }

      if "_grokparsefailure" not in [tags] and [http_path] =~ /ratings/ {
        drop { }
      }
}

output {

 elasticsearch {

    hosts => ["localhost:9200"]
    ssl_enabled => true
    ssl_verification_mode => none
    user => "elastic"
    password => "{{ lookup('amazon.aws.aws_ssm', 'elasticsearch.password', region='us-east-1' ) }}"
    index => "%{[fields][component]}-%{+yyyy-MM-dd}"

   }
}
