- name: Set Hostname For Server
  ansible.builtin.shell: set-hostname artifactory

- name: Install LVM tools
  dnf:
    name: lvm2
    state: present

- name: Get disk size of nvme0n1 or sda
  shell: |
    lsblk -bdno SIZE /dev/nvme0n1 2>/dev/null || lsblk -bdno SIZE /dev/sda 2>/dev/null
  register: disk_size
  changed_when: false

- name: Convert disk size to GB
  set_fact:
     disk_gb: "{{ (disk_size.stdout | int) // 1073741824 }}"

- name: Fail if disk size is less than 50GB
  debug:
    msg: "Disk size is {{ disk_gb }}GB. Minimum 50GB required for Artifactory."

- name: Print disk size check result
  debug:
   msg: "Disk size check : {{ disk_gb }}GB"

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - cloud-utils-growpart
      - python3-boto3
      - python3-pip
    state: installed

- name: Install python packaging module
  ansible.builtin.pip:
    name: packaging



- name: Get IMDSv2 token
  uri:
      url: http://169.254.169.254/latest/api/token
      method: PUT
      headers:
        X-aws-ec2-metadata-token-ttl-seconds: "21600"
      return_content: yes
  register: token

- name: Get instance id
  uri:
    url: http://169.254.169.254/latest/meta-data/instance-id
    headers:
      X-aws-ec2-metadata-token: "{{ token.content }}"
    return_content: yes
  register: instance_id



- name: Get volume information
  amazon.aws.ec2_vol_info:
    region: "{{ aws_region }}"
    filters:
      attachment.instance-id: "{{ instance_id.content }}"
  register: volume_info

- name: Set root volume id
  set_fact:
    root_volume: "{{ volume_info.volumes[0].id }}"

- name: Print detected volume
  debug:
   msg: "Root EBS volume is {{ root_volume }}"

- name: Expand EBS volume to 50GB
  amazon.aws.ec2_vol:
    id: "{{ root_volume }}"
    region: "{{ aws_region }}"
    size: "{{ target_size }}"
    state: present

- name: Wait for AWS to apply modification
  pause:
    seconds: 20

- name: Detect root disk
  shell: lsblk -no pkname $(df / | tail -1 | awk '{print $1}')
  register: root_disk

- name: Detect root partition
  shell: df / | tail -1 | awk '{print $1}'
  register: root_partition

- name: Expand partition
  command: growpart /dev/{{ root_disk.stdout }} 1
  ignore_errors: yes

    ############################################
    # Expand Filesystem
    ############################################

- name: Detect filesystem
  command: df -T /
  register: fs

- name: Resize XFS filesystem
  command: xfs_growfs /
  when: "'xfs' in fs.stdout"

- name: Resize EXT filesystem
  command: resize2fs "{{ root_partition.stdout }}"
  when: "'ext4' in fs.stdout"


- name: Verify new disk size
  command: df -h
  register: disk_check

- debug:
    var: disk_check.stdout_lines

- name: Copy Jfrog repo
  ansible.builtin.template:
    src: artifactory.repo
    dest: /etc/yum.repos.d/artifactory.repo

- name: Install Jfrog and Java
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - jfrog-artifactory-oss
    state: installed

- name: Fixing and enabling Non Postgres sql configuration
  ansible.builtin.template:
    src: system.yaml
    dest: /opt/jfrog/artifactory/var/etc/system.yaml

- name: Start Artifactory Service
  ansible.builtin.systemd_service:
    name: artifactory
    daemon_reload: yes
    state: started
    enabled: yes




