- name: Set Hostname For Server
  ansible.builtin.shell: set-hostname artifactory

- name: Copy Jfrog repo
  ansible.builtin.template:
    src: artifactory.repo
    dest: /etc/yum.repos.d/artifactory.repo

- name: Install Jfrog and Java
  ansible.builtin.dnf:
    name:
      - java-17-openjdk
      - jfrog-artifactory-oss
    state: installed

- name: Fixing and enabling Non Postgres sql configuration
  ansible.builtin.template:
    src: system.yaml
    dest: /opt/jfrog/artifactory/var/etc/system.yaml

- name: Start Artifactory Service
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes




